// Generated by https://quicktype.io

export interface IReport {
  extension_id: string;
  network_speed: string;
  server_access: boolean;
  pjeoffice_uninstalled: boolean;
  shodo_uninstalled: boolean;
  websigner_uninstalled: boolean;
  chrome_version?: string;
}
