// Generated by https://quicktype.io

export interface IResponseExtension {
  success: boolean;
  data: IData[];
  message: string;
}

export interface IData {
  description: string;
  enabled: boolean;
  homepageUrl: string;
  hostPermissions: string[];
  icons: IIcon[];
  id: string;
  installType: IInstallType;
  isApp: boolean;
  mayDisable: boolean;
  name: string;
  offlineEnabled: boolean;
  optionsUrl: string;
  permissions: string[];
  shortName: string;
  type: IType;
  updateUrl?: string;
  version: string;
  appLaunchUrl?: string;
  availableLaunchTypes?: string[];
  launchType?: string;
  versionName?: string;
  disabledReason?: string;
  mayEnable?: boolean;
}

export interface IIcon {
  size: number;
  url: string;
}

export enum IInstallType {
  Development = "development",
  Normal = "normal",
  Sideload = "sideload",
}

export enum IType {
  Extension = "extension",
  HostedApp = "hosted_app",
}
